const $=id=>document.getElementById(id);
const els={sound:$("soundBtn"),spin:$("spinBtn"),copy:$("copyBtn"),catE:$("catEmoji"),dishE:$("dishEmoji"),chalE:$("chalEmoji"),catT:$("catText"),dishT:$("dishText"),chalT:$("chalText"),food:$("food"),catChip:$("categoryChip"),budget:$("budgetChip"),challenge:$("challengeChip"),fortune:$("fortune"),total:$("totalSpins"),topCat:$("topCategory"),topDish:$("topDish"),hist:$("historyList")};
let data,current=null,soundOn=JSON.parse(localStorage.getItem("ljSound")??"true"),history=JSON.parse(localStorage.getItem("ljHistory")??"[]"),stats=JSON.parse(localStorage.getItem("ljStats")??'{"total":0,"categories":{},"foods":{}}');
const random=a=>a[Math.floor(Math.random()*a.length)];
function normalFoods(){return data.categories.filter(c=>!["Chaos","Lucky","Legendary","Chef's Surprise"].includes(c.name)).flatMap(c=>c.foods)}
function setSound(){els.sound.textContent=soundOn?"🔊":"🔇"}
function beep(freq=440,d=.05,type="sine"){if(!soundOn)return; const C=window.AudioContext||window.webkitAudioContext;if(!C)return; const c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=freq;o.type=type;g.gain.setValueAtTime(.045,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+d);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+d)}
function confetti(n=70){const colors=["#FFD166","#EF476F","#06D6A0","#118AB2","#C77DFF","#FF5A1F"];for(let i=0;i<n;i++){const p=document.createElement("div");p.className="confetti";p.style.left=Math.random()*100+"vw";p.style.background=random(colors);p.style.animationDelay=Math.random()*.35+"s";p.style.transform=`rotate(${Math.random()*360}deg)`;document.body.appendChild(p);setTimeout(()=>p.remove(),2300)}}
function top(obj){const e=Object.entries(obj);return e.length?e.sort((a,b)=>b[1]-a[1])[0][0]:"-"}
function save(){localStorage.setItem("ljHistory",JSON.stringify(history.slice(0,10)));localStorage.setItem("ljStats",JSON.stringify(stats))}
function panels(){els.total.textContent=stats.total||0;els.topCat.textContent=top(stats.categories);els.topDish.textContent=top(stats.foods);els.hist.innerHTML=history.length?history.map(x=>`<li>${x.food} <small>(${x.category})</small></li>`).join(""):"<li>No spins yet.</li>"}
function choose(){const category=random(data.categories);const dish=category.name==="Chef's Surprise"?random(normalFoods()):random(category.foods);return{category,dish,challenge:random(data.challenges),fortune:random(data.fortunes)}}
function shuffleText(){const c=random(data.categories);els.catE.textContent=c.emoji;els.catT.textContent=c.name;els.dishE.textContent=random(["🍛","🍜","🥟","🍔","🍕","🍣","🥗","🍱","⚡","🌮"]);els.dishT.textContent=random(normalFoods());els.chalE.textContent=random(["🎯","👥","🌶️","💰","📸","⭐","🎲"]);els.chalT.textContent=random(data.challenges)}
function record(r){stats.total=(stats.total||0)+1;stats.categories[r.category.name]=(stats.categories[r.category.name]||0)+1;stats.foods[r.dish]=(stats.foods[r.dish]||0)+1;history.unshift({food:r.dish,category:r.category.name,time:new Date().toISOString()});history=history.slice(0,10);save();panels()}
function reveal(r){current=r;els.catE.textContent=r.category.emoji;els.catT.textContent=r.category.name;els.dishE.textContent=r.category.emoji;els.dishT.textContent=r.dish;els.chalE.textContent="🎯";els.chalT.textContent=r.challenge;els.food.textContent=r.dish;els.catChip.textContent=`${r.category.emoji} ${r.category.name}`;els.budget.textContent=`💰 ${r.category.budget}`;els.challenge.textContent=`🎯 ${r.challenge}`;els.fortune.textContent=r.fortune;record(r);beep(660,.08,"triangle");setTimeout(()=>beep(880,.1,"triangle"),90);if(["Lucky","Legendary","Chef's Surprise"].includes(r.category.name))confetti(90)}
function spin(){els.spin.disabled=true;document.querySelectorAll(".reel").forEach(r=>r.classList.add("spinning"));els.food.textContent="Spinning...";els.fortune.textContent="The lunch machine is shuffling destiny.";const r=choose();let ticks=0;const t=setInterval(()=>{shuffleText();beep(260+ticks*16,.025,"square");ticks++;if(ticks>24){clearInterval(t);document.querySelectorAll(".reel").forEach(x=>x.classList.remove("spinning"));reveal(r);els.spin.disabled=false}},95)}
async function copy(){const text=current?`🎰 Lunch Jackpot: ${current.dish} (${current.category.name}) • ${current.category.budget} • ${current.challenge}`:"🎰 Lunch Jackpot: Not spun yet";try{await navigator.clipboard.writeText(text);els.copy.textContent="✅";setTimeout(()=>els.copy.textContent="📋",1000)}catch{alert(text)}}
async function init(){data=await fetch("./foods.json").then(r=>r.json());setSound();panels();els.spin.addEventListener("click",spin);els.copy.addEventListener("click",copy);els.sound.addEventListener("click",()=>{soundOn=!soundOn;localStorage.setItem("ljSound",JSON.stringify(soundOn));setSound()});document.querySelectorAll(".tab").forEach(tab=>tab.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(t=>t.classList.remove("active"));document.querySelectorAll(".panel").forEach(p=>p.classList.remove("active"));tab.classList.add("active");$(tab.dataset.tab+"Panel").classList.add("active")}))}
init();
