const el={soundBtn:document.getElementById('soundBtn'),spinBtn:document.getElementById('spinBtn'),copyBtn:document.getElementById('copyBtn'),catE:document.getElementById('reelCategory'),dishE:document.getElementById('reelDish'),chalE:document.getElementById('reelChallenge'),catT:document.getElementById('reelCategoryText'),dishT:document.getElementById('reelDishText'),chalT:document.getElementById('reelChallengeText'),food:document.getElementById('food'),catChip:document.getElementById('categoryChip'),budgetChip:document.getElementById('budgetChip'),chalChip:document.getElementById('challengeChip'),fortune:document.getElementById('fortune'),total:document.getElementById('totalSpins'),topCat:document.getElementById('topCategory'),topDish:document.getElementById('topDish'),history:document.getElementById('historyList')};
let data,current=null,soundOn=JSON.parse(localStorage.getItem('lunchJackpotSound')??'true'),history=JSON.parse(localStorage.getItem('lunchJackpotHistory')??'[]'),stats=JSON.parse(localStorage.getItem('lunchJackpotStats')??'{"total":0,"categories":{},"foods":{}}');
const rand=a=>a[Math.floor(Math.random()*a.length)];
const regularFoods=()=>data.categories.filter(c=>!['Chaos','Lucky','Legendary',"Chef's Surprise"].includes(c.name)).flatMap(c=>c.foods);
function beep(freq=440,duration=.06,type='sine'){if(!soundOn)return;const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const ctx=new A(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=freq;osc.type=type;gain.gain.setValueAtTime(.05,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+duration);osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+duration)}
function setSound(){el.soundBtn.textContent=soundOn?'🔊':'🔇'}
function confetti(n=70){const colors=['#FFD166','#EF476F','#06D6A0','#118AB2','#C77DFF','#FF5A1F'];for(let i=0;i<n;i++){const p=document.createElement('div');p.className='confetti';p.style.left=Math.random()*100+'vw';p.style.background=rand(colors);p.style.animationDelay=Math.random()*.35+'s';p.style.transform=`rotate(${Math.random()*360}deg)`;document.body.appendChild(p);setTimeout(()=>p.remove(),2300)}}
function save(){localStorage.setItem('lunchJackpotHistory',JSON.stringify(history.slice(0,10)));localStorage.setItem('lunchJackpotStats',JSON.stringify(stats))}
function top(obj){const e=Object.entries(obj);return e.length?e.sort((a,b)=>b[1]-a[1])[0][0]:'-'}
function update(){el.total.textContent=stats.total||0;el.topCat.textContent=top(stats.categories);el.topDish.textContent=top(stats.foods);el.history.innerHTML=history.length?history.map(x=>`<li>${x.food} <small>(${x.category})</small></li>`).join(''):'<li>No spins yet.</li>'}
function choose(){const category=rand(data.categories),dish=category.name==="Chef's Surprise"?rand(regularFoods()):rand(category.foods),challenge=rand(data.challenges),fortune=rand(data.fortunes);return{category,dish,challenge,fortune}}
function shuffleText(){const c=rand(data.categories);el.catE.textContent=c.emoji;el.catT.textContent=c.name.split(' ')[0];el.dishE.textContent=rand(['🍛','🍜','🥟','🍔','🍕','🍣','🥗','🍱','⚡','🌮']);el.dishT.textContent=rand(regularFoods()).split(' ').slice(0,2).join(' ');el.chalE.textContent=rand(['🎯','👥','🌶️','💰','📸','⭐','🎲']);el.chalT.textContent=rand(data.challenges).split(' ').slice(0,2).join(' ')}
function record(r){stats.total=(stats.total||0)+1;stats.categories[r.category.name]=(stats.categories[r.category.name]||0)+1;stats.foods[r.dish]=(stats.foods[r.dish]||0)+1;history.unshift({food:r.dish,category:r.category.name,time:new Date().toISOString()});history=history.slice(0,10);save();update()}
function reveal(r){current=r;el.catE.textContent=r.category.emoji;el.catT.textContent=r.category.name;el.dishE.textContent=r.category.emoji;el.dishT.textContent=r.dish;el.chalE.textContent='🎯';el.chalT.textContent=r.challenge;el.food.textContent=r.dish;el.catChip.textContent=`${r.category.emoji} ${r.category.name}`;el.budgetChip.textContent=`💰 ${r.category.budget}`;el.chalChip.textContent=`🎯 ${r.challenge}`;el.fortune.textContent=r.fortune;record(r);beep(660,.08,'triangle');setTimeout(()=>beep(880,.1,'triangle'),90);if(['Lucky',"Chef's Surprise",'Legendary'].includes(r.category.name))confetti(90)}
function spin(){el.spinBtn.disabled=true;document.querySelectorAll('.reel').forEach(r=>r.classList.add('spinning'));el.food.textContent='Spinning...';el.fortune.textContent='The lunch machine is shuffling destiny.';const result=choose();let ticks=0;const int=setInterval(()=>{shuffleText();beep(280+ticks*18,.025,'square');ticks++;if(ticks>26){clearInterval(int);document.querySelectorAll('.reel').forEach(r=>r.classList.remove('spinning'));reveal(result);el.spinBtn.disabled=false}},95)}
async function copy(){const text=current?`🎰 Lunch Jackpot: ${current.dish} (${current.category.name}) • ${current.category.budget} • ${current.challenge}`:'🎰 Lunch Jackpot: Not spun yet';try{await navigator.clipboard.writeText(text);el.copyBtn.textContent='✅';setTimeout(()=>el.copyBtn.textContent='📋',1000)}catch{alert(text)}}
async function init(){data=await fetch('./foods.json').then(r=>r.json());setSound();update();el.spinBtn.addEventListener('click',spin);el.copyBtn.addEventListener('click',copy);el.soundBtn.addEventListener('click',()=>{soundOn=!soundOn;localStorage.setItem('lunchJackpotSound',JSON.stringify(soundOn));setSound()});document.querySelectorAll('.tab').forEach(t=>t.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));t.classList.add('active');document.getElementById(`${t.dataset.tab}Panel`).classList.add('active')}))}
init();
